version: '3'
networks:
  external:
  internal:
services:
  nginx:
    depends_on:
        - traefik
    image: nginx:latest
    labels:
        - traefik.http.routers.dropgame.entrypoints=websecure
        - traefik.http.routers.dropgame.rule=Host(`localhost`)
        - traefik.http.routers.dropgame.service=dropgame
        - traefik.http.routers.dropgame.tls=true
        - traefik.http.services.dropgame.loadbalancer.server.port=80
    restart: unless-stopped
    volumes:
        - ./html:/usr/share/nginx/html:ro
  traefik:
    image: traefik:2.6
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./traefik.yml:/traefik.yml:ro
      - /etc/localtime:/etc/localtime.ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
