name: Publish site
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish site
      run: |
        wget https://github.com/tmijs/tmi.js/releases/download/v1.8.5/tmi.min.js -O ./drop-game/static/tmi.min.js
        mv ./drop-game/static ./docs
        git config user.email git@github.com
        git config user.name 'GitHub Actions'
        git add .
        git commit -m 'Publish site'
        git push -f -u origin master:gh-pages
